-- 마이그레이션 확인
-- 아래의 쿼리를 전부 복사하여 확인을 진행하면됩니다. 회원 마이그레이션이 진행되었을때에는 아래의 쿼리로만 확인을 진행하시면 무방합니다.
-- BSTR_REG_NO = '' 또는 BIZ_NO = '' 라고 적혀있는 곳 중 '' 안에 '9999999999' 과 같이 사업자번호를 입력하시면 조회가 가능합니다.

-- MEMB_NM(회원명)
-- JUMIN_NO(생년월일)
-- STAT_CD(회원상태) : 02
-- PERM_CD(권한코드) : 00 - 대표법무사 , 03 - 대표 이외 법무사
-- REPT_YN(대표여부) : Y - 대표법무사 , N - 대표 이외 법무사
SELECT MEMB_NM, JUMIN_NO, STAT_CD, PERM_CD, REPT_YN, BIZ_NO, TRREG_PSSB_YN 
  FROM TB_CUST_MASTER_TEMP
 WHERE BIZ_NO = '1310482134'
;
-- ASIS와 비교를 하고 싶다면 아래의 쿼리를 이용하면된다.
-- (MEMB_STAT_CD = 01) => (STAT_CD = 02)
-- QUAL_CD : 210 (대표), 220 (소속)
SELECT MEMB_NM, MEMB_IDFT_CHECK AS JUMIN_NO, MEMB_STAT_CD AS STAT_CD
     , CASE WHEN QUAL_CD = '210' THEN '00' 
            ELSE '03'
       END AS PERM_CD
     , CASE WHEN QUAL_CD = '210' THEN 'Y' 
            ELSE 'N'
       END AS REPT_YN
     , BSTR_REG_NO AS BIZ_NO
  FROM ES1MC0100M 
 WHERE BSTR_REG_NO = ''

 
 
-- ACCT_DSC(01), BANK_CD(020) 은행정보가 1개라도 존재하는지 확인
SELECT *
  FROM TB_CUST_ACCT_INFO_TEMP
 WHERE BIZ_NO = ''
;
-- ASIS에서는 아래의 테이블에 저장되어있다
SELECT A.*
  FROM BK1MC0200M A
  JOIN ES1MC0100M B ON A.REPT_MEMB_NO = B.MEMB_NO AND B.QUAL_CD = '210'
 WHERE B.BSTR_REG_NO = ''
;


-- TB_CUST_MASTER 사업자 별 회원수 * 8 개의 로우가 생성되었는지 확인
SELECT *
  FROM TB_CUST_AGREEMENT_HIST_TEMP A
  JOIN TB_CUST_MASTER_TEMP B ON A.MEMB_NO = B.MEMB_NO
 WHERE B.BIZ_NO = ''
;

-- 1개의 로우가 생성되었는지 확인
SELECT * 
  FROM TB_CUST_OFFICE_ESTM_TEMP
 WHERE BIZ_NO = ''
;
 
-- TB_CUST_MASTER 사업자 별 회원수 * 5 개의 로우가 생성되었는지 확인
SELECT *
  FROM TB_CUST_ALM_TEMP A
  JOIN TB_CUST_MASTER_TEMP B ON A.MEMB_NO = B.MEMB_NO
 WHERE B.BIZ_NO = ''
;

-- 1개의 로우가 생성되었는지 확인
SELECT *
  FROM TB_SYST_OFFICE_BACKUP_TEMP
 WHERE BIZ_NO = ''
;

-- OFFICE_NM
-- OFFICE_ADDR
-- REPT_MEMB_NO
-- OFFICE_TELNO
-- OFFICE_TYPE
-- ELREG_ID 존재하지 않을수도 있음.
-- STAT_CD : 02
SELECT OFFICE_NM, OFFICE_ADDR, REPT_MEMB_NO, OFFICE_TELNO, OFFICE_TYPE, ELREG_ID, STAT_CD
  FROM TB_CUST_OFFICE_TEMP
 WHERE BIZ_NO = ''
;
SELECT A.CPNM_NM AS OFFICE_NM , A.BIZP_ADDR AS OFFICE_ADDR, B.MEMB_NO AS REPT_MEMB_NO ,CONCAT(C.REGN_NO,C.BRU_NO,C.ECH_NO) AS OFFICE_TELNO,A.BSTR_DVSN_CD AS OFFICE_TYPE, B.E_FORM_ID AS ELREG_ID
  FROM ES1MC0904M A
  LEFT JOIN ES1MC0100M B ON A.BSTR_REG_NO = B.BSTR_REG_NO AND B.QUAL_CD = '210'
  LEFT JOIN ES1MC0201D C ON B.MEMB_NO = C.MEMB_NO AND C.ADDR_CTIF_DVSN_CD = '04'
 WHERE A.BSTR_REG_NO = ''
;
